[package]
name = "hw2_conrod"
version = "0.1.2"
authors = ["illemonati <you@example.com>"]

[dependencies]
find_folder="0.3"

[dependencies.conrod]
version = "0.61"
features = [
    "glium",
    "winit",
]
